### ISSUE TITLE
missing Normalization in Attention

### ISSUE THREAD

**Issue by nkjack** [hila-chefer/Transformer-Explainability#10]
Hi,

First, thank you for the great work! 
I'm not sure if I missed It or not, but according to your paper, you use normalization on (R_j)^u and (R_k)^v and I could not find it in the code (https://github.com/hila-chefer/Transformer-Explainability/blob/bbb4b86a62677bc2be0d809b15349addca78d244/BERT_explainability/modules/BERT/BERT.py#L367).

I couldn't find normalization in your MatMul module as well (https://github.com/hila-chefer/Transformer-Explainability/blob/bbb4b86a62677bc2be0d809b15349addca78d244/BERT_explainability/modules/layers_ours.py#L89)

Is that intentional, or am I missing something?

Thanks a lot!
Best.

**Comment by hila-chefer** [comment]
Hi @nkjack thanks for your interest in our work, and thanks for the great question- I was wondering if/ when anyone is going to ask it :)
If you look at our normalization method when it comes to the matrix multiplication operation we will get two attribution maps, for each of the matrices we multiply, and the sum of the relevancies of each matrix will be R. 
So actually to normalize the cams, all we need to do is divide each cam by 2 (which is what the normalization does since both (R_j)^u and (R_k)^v have the same sum). In contrast to the add layer, we didn't do that in the [layers implementation](https://github.com/hila-chefer/Transformer-Explainability/blob/main/modules/layers_ours.py), we simply incorporated that in the relprop itself. In [this example](https://github.com/hila-chefer/Transformer-Explainability/blob/main/baselines/ViT/ViT_LRP.py#L161) for ViT you can see it in action (lines 161-162), we divide each of the cams by 2 after the matmul operation, which is identical to applying our normalization.
It is important to notice that this is the case for matmul only, for add layers, the sums of the two relevancies may not be equal, as we point out in the paper.
I do hope this answers your question, but if not please feel free to ask for clarifications if necessary.

**Comment by nkjack** [comment]
Amazing! thank you, it's all clear now
