### ISSUE TITLE
visualize TimeSformer

### ISSUE THREAD

**Issue by Holmes-Alan** [hila-chefer/Transformer-Explainability#24]
Hello, do you think that you can show one example of using your code for TimeSformer visualization?

**Comment by hila-chefer** [comment]
Hi @Holmes-Alan, thanks for your interest in our work!
I’m not really familiar with TimeSformer, so adding it to this repo isn’t planned.
If the implementation is similar to either ViT or BERT, you can use the LRP layers implemented in this project. Otherwise, we have a [follow up work](https://github.com/hila-chefer/Transformer-MM-Explainability) that just got accepted to ICCV which eliminates the use of LRP making it significantly simpler to implement.

I’ll be happy to help with any other questions regarding the implementation itself.
Best,
Hila.

**Comment by mohamedmansour0** [comment]
@Holmes-Alan have you found a way to visualize the Timesformer attention?

**Comment by Holmes-Alan** [comment]
no, I am not sure how to do it.
