### ISSUE TITLE
Question about `no_weight_decay` in the code of ViT

### ISSUE THREAD

**Issue by yztongzhan** [hila-chefer/Transformer-Explainability#3]
Hi @hila-chefer, I have a question about the `no_weight_decay` function below:
https://github.com/hila-chefer/Transformer-Explainability/blob/23cac8e66c846454d59af4b1caac241626897077/baselines/ViT/ViT_new.py#L189-L191
I think it make sense to perform `no_weight_decay` for the parameters of embeddings, but I didn't find the reference of this function in your repo. Will you explain it for me? 
Thanks :)

**Comment by hila-chefer** [comment]
Hi @yztongzhan, thanks for your question 👍 
For ViT implementation, I'm using this repo: 
https://github.com/rwightman/pytorch-image-models
(which is a great resource in general in my opinion).
`no_weight_decay` is not in use because I don't actually train the model (i.e., I don't initialize an optimizer), I used the pretrained weights.
I hope this answers your question, I'll update the code soon with a cleanup and remove all unused code to eliminate confusions.

**Comment by yztongzhan** [comment]
Thanks for your reply! ☺️
